# Generated by Django 3.1 on 2020-08-31 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagages', '0002_auto_20200831_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='Content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
