# Generated by Django 3.1 on 2020-08-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(related_name='Obtener_publicaciones', to='blog.Categoria', verbose_name='Categorias'),
        ),
    ]
