# Generated by Django 3.1.1 on 2020-09-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messange',
            options={'ordering': ['created'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Hilo de conversacion', 'verbose_name_plural': 'Hilos de conversacion'},
        ),
    ]
