# Generated by Django 3.1.1 on 2020-09-11 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0002_auto_20200911_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='users',
            field=models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
